FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache wget

COPY package*.json ./
RUN npm ci --only=production

COPY . .

RUN wget https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem \
    -O rds-combined-ca-bundle.pem

EXPOSE 5000

CMD ["node", "server.js"]
